openapi: 3.0.2
info:
    title: LocationAPI
    version: 1.0.0
    description: A brand new API with no content.  Go nuts!
paths:
    /locations:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Location'
                            examples:
                                all:
                                    value:
                                        -
                                            id: 1
                                            name: International Inc Corporate Office
                                            location:
                                                lat: 51.5013673
                                                lng: -0.1440787
                                            type: headquarter
                                            status: '1'
                                        -
                                            id: 2
                                            name: International Inc North America
                                            location:
                                                lat: 40.6976701
                                                lng: -74.259876
                                            type: office
                                            status: '1'
                                        -
                                            id: 3
                                            name: International Inc France
                                            location:
                                                lat: 48.859
                                                lng: 2.2069746
                                            type: office
                                            status: '1'
                    description: API to return all locations
    '/locations/{id}':
        get:
            parameters:
                -
                    examples:
                        '1':
                            value: '1'
                    name: id
                    schema:
                        format: int32
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Location'
                            examples:
                                '1':
                                    value:
                                        id: 1
                                        name: some text
                                        location:
                                            lat: 75.4
                                            lng: 45.75
                                        type: some text
                                        status: some text
components:
    schemas:
        Location:
            title: Root Type for Location
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                location:
                    type: object
                    properties:
                        lat:
                            format: double
                            type: number
                        lng:
                            format: double
                            type: number
                type:
                    type: string
                status:
                    type: string
            example:
                id: 1
                name: International Inc Corporate Office
                location:
                    lat: 51.5013673
                    lng: -0.1440787
                type: headquarter
                status: '1'
