apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/open-sudo/3scale-gitops.git
    path: products
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: threescale
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true       
    retry:
      limit: 50 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 10m 
